global:
  slack_api_url: $SLACK_WEBHOOK_URL

route:
  group_by: ['alertname']
  repeat_interval: 1m
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#alerts'
    title: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}'
    text: '{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']